export const dashboardData = {
  adminUtama: [
    {
      id: 1,
      kodePost: "12345",
      namaDaerah: "Daerah A",
      jumlahPengguna: 1000,
      pengeluaranAir: 500,
    },
    {
      id: 2,
      kodePost: "67890",
      namaDaerah: "Daerah B",
      jumlahPengguna: 1500,
      pengeluaranAir: 750,
    },
    {
      id: 3,
      kodePost: "67890",
      namaDaerah: "Daerah C",
      jumlahPengguna: 1500,
      pengeluaranAir: 750,
    },
    {
      id: 4,
      kodePost: "67890",
      namaDaerah: "Daerah D",
      jumlahPengguna: 1500,
      pengeluaranAir: 750,
    },
    {
      id: 5,
      kodePost: "12345",
      namaDaerah: "Daerah A",
      jumlahPengguna: 1000,
      pengeluaranAir: 500,
    },
    {
      id: 6,
      kodePost: "67890",
      namaDaerah: "Daerah B",
      jumlahPengguna: 1500,
      pengeluaranAir: 750,
    },
    {
      id: 7,
      kodePost: "67890",
      namaDaerah: "Daerah C",
      jumlahPengguna: 1500,
      pengeluaranAir: 750,
    },
    {
      id: 8,
      kodePost: "67890",
      namaDaerah: "Daerah D",
      jumlahPengguna: 1500,
      pengeluaranAir: 750,
    },
    {
      id: 9,
      kodePost: "12345",
      namaDaerah: "Daerah A",
      jumlahPengguna: 1000,
      pengeluaranAir: 500,
    },
    {
      id: 10,
      kodePost: "67890",
      namaDaerah: "Daerah B",
      jumlahPengguna: 1500,
      pengeluaranAir: 750,
    },
    {
      id: 11,
      kodePost: "67890",
      namaDaerah: "Daerah C",
      jumlahPengguna: 1500,
      pengeluaranAir: 750,
    },
    {
      id: 12,
      kodePost: "67890",
      namaDaerah: "Daerah D",
      jumlahPengguna: 1500,
      pengeluaranAir: 750,
    },
    {
      id: 13,
      kodePost: "12345",
      namaDaerah: "Daerah A",
      jumlahPengguna: 1000,
      pengeluaranAir: 500,
    },
    {
      id: 14,
      kodePost: "67890",
      namaDaerah: "Daerah B",
      jumlahPengguna: 1500,
      pengeluaranAir: 750,
    },
    {
      id: 15,
      kodePost: "67890",
      namaDaerah: "Daerah C",
      jumlahPengguna: 1500,
      pengeluaranAir: 750,
    },
    {
      id: 16,
      kodePost: "67890",
      namaDaerah: "Daerah D",
      jumlahPengguna: 1500,
      pengeluaranAir: 750,
    },
    {
      id: 17,
      kodePost: "12345",
      namaDaerah: "Daerah A",
      jumlahPengguna: 1000,
      pengeluaranAir: 500,
    },
    {
      id: 18,
      kodePost: "67890",
      namaDaerah: "Daerah B",
      jumlahPengguna: 1500,
      pengeluaranAir: 750,
    },
    {
      id: 19,
      kodePost: "67890",
      namaDaerah: "Daerah C",
      jumlahPengguna: 1500,
      pengeluaranAir: 750,
    },
    {
      id: 20,
      kodePost: "67890",
      namaDaerah: "Daerah D",
      jumlahPengguna: 1500,
      pengeluaranAir: 750,
    },
    {
      id: 21,
      kodePost: "12345",
      namaDaerah: "Daerah A",
      jumlahPengguna: 1000,
      pengeluaranAir: 500,
    },
    {
      id: 22,
      kodePost: "67890",
      namaDaerah: "Daerah B",
      jumlahPengguna: 1500,
      pengeluaranAir: 750,
    },
    {
      id: 23,
      kodePost: "67890",
      namaDaerah: "Daerah C",
      jumlahPengguna: 1500,
      pengeluaranAir: 750,
    },
    {
      id: 24,
      kodePost: "67890",
      namaDaerah: "Daerah D",
      jumlahPengguna: 1500,
      pengeluaranAir: 750,
    },
    // Add more data rows for Admin Utama
  ],
  adminDaerah: [
    {
      id: 1,
      nik: "A123",
      nama: "Admin Daerah 1",
      pengeluaranAir: 300,
    },
    {
      id: 2,
      nik: "B456",
      nama: "Admin Daerah 2",
      pengeluaranAir: 450,
    },
    {
      id: 3,
      nik: "A123",
      nama: "Admin Daerah 1",
      pengeluaranAir: 300,
    },
    {
      id: 4,
      nik: "B456",
      nama: "Admin Daerah 2",
      pengeluaranAir: 450,
    },
    // Add more data rows for Admin Daerah
  ],
  pengguna: [
    {
      id: 1,
      tanggal: "2023-07-01",
      pengeluaranAir: 50,
    },
    {
      id: 2,
      tanggal: "2023-07-02",
      pengeluaranAir: 70,
    },
    {
      id: 3,
      tanggal: "2023-07-01",
      pengeluaranAir: 50,
    },
    {
      id: 4,
      tanggal: "2023-07-02",
      pengeluaranAir: 70,
    },
    // Add more data rows for Pengguna
  ],
};
